receivers:
  otlp:
    protocols:
      grpc: {endpoint: '0.0.0.0:4317'}
      http: {endpoint: '0.0.0.0:4318'}
extensions:
  health_check: {endpoint: '0.0.0.0:13133'}
processors:
  batch: {}
exporters:
  elasticsearch:
    endpoints: [http://elasticsearch:9200]
    logs_index: infraaxon-logs
    traces_index: infraaxon-traces
    mapping: {mode: ecs}
  prometheus:
    endpoint: '0.0.0.0:8889'
    resource_to_telemetry_conversion: {enabled: true}
service:
  extensions: [health_check]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus: {host: '0.0.0.0', port: 8888}
  pipelines:
    logs: {receivers: [otlp], processors: [batch], exporters: [elasticsearch]}
    traces: {receivers: [otlp], processors: [batch], exporters: [elasticsearch]}
    metrics: {receivers: [otlp], processors: [batch], exporters: [prometheus]}
