<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { defineStore } from 'pinia'
import { useRouter } from 'vue-router'
interface Product{id:string;name:string;category:string;description:string;priceKopecks:number;imageKey:string}
interface Order{id:string;status:string;totalKopecks:number;items:{name:string;quantity:number;unitPriceKopecks:number}[]}
const useCart=defineStore('cart',{state:()=>({lines:JSON.parse(localStorage.getItem('forma-cart')||'[]') as {product:Product;quantity:number}[]})})
const cart=useCart(),router=useRouter(),products=ref<Product[]>([]),search=ref(''),category=ref(''),page=ref(1),total=ref(0),view=ref('catalog'),detail=ref<Product|null>(null),order=ref<Order|null>(null),name=ref(''),address=ref(''),error=ref(''),busy=ref(false)
const idempotency=ref(crypto.randomUUID()),count=computed(()=>cart.lines.reduce((n,l)=>n+l.quantity,0)),amount=computed(()=>cart.lines.reduce((n,l)=>n+l.quantity*l.product.priceKopecks,0))
const money=(n:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n/100)
let interval:ReturnType<typeof setInterval>
watch(()=>cart.lines,()=>{localStorage.setItem('forma-cart',JSON.stringify(cart.lines));idempotency.value=crypto.randomUUID()},{deep:true})
async function api(path:string,options?:RequestInit){const response=await fetch(path,options);if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'Сервис временно недоступен. Попробуйте ещё раз.')}return response.json()}
async function load(){busy.value=true;error.value='';try{const result=await api('/api/products?'+new URLSearchParams({search:search.value,category:category.value,page:String(page.value)}));products.value=result.items;total.value=result.total}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function go(next:string){view.value=next;router.replace({query:{view:next,...(next==='order'&&order.value?{order:order.value.id}:{})}})}
function add(p:Product){const line=cart.lines.find(l=>l.product.id===p.id);if(line){if(line.quantity<100)line.quantity++}else cart.lines.push({product:p,quantity:1});detail.value=null}
async function checkout(){busy.value=true;error.value='';try{order.value=await api('/api/orders',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotency.value},body:JSON.stringify({items:cart.lines.map(l=>({productId:l.product.id,quantity:l.quantity})),customerName:name.value,address:address.value})});cart.lines=[];go('order')}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function poll(){if(order.value&&order.value.status!=='completed'){try{order.value=await api('/api/orders/'+order.value.id);error.value=''}catch(e){error.value=(e as Error).message}}}
onMounted(async()=>{await load();const id=new URLSearchParams(location.search).get('order');if(id){try{order.value=await api('/api/orders/'+encodeURIComponent(id));go('order')}catch(e){error.value=(e as Error).message}}interval=setInterval(poll,2500)})
onUnmounted(()=>clearInterval(interval))
</script>
<template><div class="announcement">Маленькие детали. Большие перемены.</div><header><a href="/" class="logo">forma<span>®</span></a><nav><button @click="go('catalog')">Каталог</button><span>Для работы и жизни</span></nav><button class="cart-button" @click="go('cart')">Корзина <b>{{count}}</b></button></header><main><p v-if="error" role="alert" class="error">{{error}}</p>
<template v-if="view==='catalog'"><section class="hero"><div><div class="eyebrow">THE EVERYDAY COLLECTION / 2026</div><h1>Вещи, которые<br>задают <em>ритм.</em></h1><p>Продуманные предметы для вашего пространства.<br>Меньше лишнего. Больше своего.</p><a class="dark" href="#catalog">Найти своё ↗</a></div><div class="hero-art"><div class="circle"></div><div class="object"><span></span></div><small>DESIGNED FOR YOUR EVERYDAY</small></div></section><section id="catalog"><div class="catalog-heading"><div><span class="eyebrow">CURATED ESSENTIALS</span><h2>Новая повседневность <small>{{total}}</small></h2></div><form @submit.prevent="page=1;load()"><input v-model="search" placeholder="Найти вещь…" aria-label="Поиск товаров"><button aria-label="Найти">⌕</button></form></div><div class="filters"><button v-for="c in ['', 'Рабочее место','Электроника','Аксессуары']" :key="c" :class="{active:category===c}" @click="category=c;page=1;load()">{{c||'Все предметы'}}</button><span v-if="busy">Загружаем…</span></div><div class="products"><article v-for="p in products" :key="p.id"><button class="picture" @click="detail=p"><img :src="`/api/products/${p.id}/image`" :alt="p.name" loading="lazy"><span>Подробнее ↗</span></button><div class="product-meta"><div><small>{{p.category}}</small><h3>{{p.name}}</h3></div><button class="add" :aria-label="`Добавить ${p.name}`" @click="add(p)">＋</button></div><strong>{{money(p.priceKopecks)}}</strong></article></div><p v-if="!busy&&!products.length" class="empty">Товары не найдены.</p><div class="pagination"><button :disabled="page===1" @click="page--;load()">← Назад</button><span>{{page}} / {{Math.max(1,Math.ceil(total/12))}}</span><button :disabled="page*12>=total" @click="page++;load()">Далее →</button></div></section></template>
<section v-if="view==='cart'" class="checkout"><div><span class="eyebrow">YOUR SELECTION</span><h1>Ваша корзина</h1><div v-if="!count" class="empty"><p>Пока здесь ничего нет.</p><button class="dark" @click="go('catalog')">В каталог →</button></div><article v-for="(line,i) in cart.lines" :key="line.product.id" class="cart-line"><img :src="`/api/products/${line.product.id}/image`" :alt="line.product.name"><div><h3>{{line.product.name}}</h3><span>{{money(line.product.priceKopecks)}}</span><label>Количество <input type="number" min="1" max="100" v-model.number="line.quantity"></label></div><button @click="cart.lines.splice(i,1)" :aria-label="`Удалить ${line.product.name}`">×</button></article></div><form v-if="count" class="checkout-form" @submit.prevent="checkout"><h2>Оформление заказа</h2><label>Имя<input v-model="name" required maxlength="120" autocomplete="name"></label><label>Адрес доставки<textarea v-model="address" required maxlength="500" autocomplete="street-address"></textarea></label><div class="total"><span>Итого</span><strong>{{money(amount)}}</strong></div><p>Демонстрационный магазин: оплата и доставка имитируются. Деньги не списываются.</p><button class="dark" :disabled="busy">{{busy?'Оформляем…':'Оформить заказ →'}}</button></form></section>
<section v-if="view==='order'&&order" class="order"><div class="eyebrow">THANK YOU</div><h1>Заказ принят.</h1><p>Номер: {{order.id}}</p><div class="steps"><div v-for="(s,i) in ['accepted','processing','completed']" :key="s" :class="{done:['accepted','processing','completed'].indexOf(order.status)>=i}"><b>{{i+1}}</b><span>{{['Принят','Обрабатывается','Готов'][i]}}</span></div></div><p v-if="order.status==='completed'">Всё готово! Спасибо за демонстрационную покупку.</p><p v-else>Статус обновляется автоматически.</p><div class="order-items"><div v-for="line in order.items" :key="line.name"><span>{{line.name}} × {{line.quantity}}</span><strong>{{money(line.unitPriceKopecks*line.quantity)}}</strong></div><div class="total"><span>Итого</span><strong>{{money(order.totalKopecks)}}</strong></div></div><button class="dark" @click="go('catalog')">Продолжить покупки →</button></section>
</main><footer><span class="logo">forma®</span><span>Вещи для вашего ритма.</span><small>Демонстрационное приложение InfraAxon</small></footer><div v-if="detail" class="overlay" @click.self="detail=null"><article class="product-modal"><button class="close" aria-label="Закрыть товар" @click="detail=null">×</button><img :src="`/api/products/${detail.id}/image`" :alt="detail.name"><div><small>{{detail.category}}</small><h2>{{detail.name}}</h2><p>{{detail.description}}</p><h3>{{money(detail.priceKopecks)}}</h3><button class="dark" @click="add(detail)">Добавить в корзину ＋</button></div></article></div></template>
