import { test, expect } from '@playwright/test'
test('operator creates an environment and registers an independent HTTP target',async({page})=>{
  test.skip(!process.env.PLATFORM_KEY,'Set PLATFORM_KEY to test against a running platform')
  await page.goto('/')
  await page.getByRole('textbox',{name:'Ключ оператора'}).fill(process.env.PLATFORM_KEY!)
  await page.getByRole('button',{name:'Войти в платформу →'}).click()
  await page.getByRole('button',{name:'＋ Новое окружение'}).click()
  const name='E2E '+Date.now()
  await page.getByRole('textbox',{name:'Название окружения',exact:true}).fill(name)
  await page.getByRole('button',{name:'Сохранить',exact:true}).click()
  await expect(page.getByRole('combobox',{name:'Окружение'})).toContainText(name)
  await page.getByRole('button',{name:'＋ Подключить компонент'}).click()
  await page.getByRole('textbox',{name:'Название',exact:true}).fill('Independent HTTP')
  await page.getByRole('textbox',{name:'Endpoint',exact:true}).fill('http://platform:8000')
  await page.getByRole('checkbox',{name:'Запустить специализированного агента'}).uncheck()
  await page.getByRole('button',{name:'Сохранить',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Independent HTTP'})).toBeVisible()
  await page.getByRole('heading',{name:'Independent HTTP'}).click()
  await page.getByRole('button',{name:'Проверить',exact:true}).click()
  await expect(page.getByText('Последнее наблюдение')).toBeVisible()
})
test('shop checkout reaches a completed order',async({page})=>{
  await page.goto('http://localhost:18081')
  await page.getByRole('button',{name:'Добавить Arc desk lamp',exact:true}).click()
  await page.getByRole('button',{name:'Корзина 1'}).click()
  await page.getByRole('textbox',{name:'Имя',exact:true}).fill('Synthetic buyer')
  await page.getByRole('textbox',{name:'Адрес доставки',exact:true}).fill('Demo address')
  await page.getByRole('button',{name:'Оформить заказ →'}).click()
  await expect(page.getByRole('heading',{name:'Заказ принят.'})).toBeVisible()
  await expect(page.getByText('Всё готово! Спасибо за демонстрационную покупку.')).toBeVisible({timeout:60000})
})
