server {
  listen 80;
  root /usr/share/nginx/html;
  location /api/products { proxy_pass http://catalog:8080; }
  location /api/orders { proxy_pass http://orders:8080; }
  location / { try_files $uri $uri/ /index.html; }
}
