<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useWorkspace } from './store'
import { api, type Environment, type Component, type Adapter, type Investigation } from './api'
const workspace = useWorkspace(), router = useRouter()
const authenticated = ref(false), loginKey = ref(''), busy = ref(false), error = ref('')
const environments = ref<Environment[]>([]), components = ref<Component[]>([]), adapters = ref<Adapter[]>([]), history = ref<Investigation[]>([])
const selected = ref<Component | null>(null), investigation = ref<Investigation | null>(null), question = ref(''), target = ref(''), trace = ref('')
const modal = ref<'environment' | 'component' | null>(null), editing = ref(''), envName = ref(''), envDescription = ref('')
const form = ref({name: '', type: 'http', endpoint: '', web_url: '', description: '', enabled: true, dependencies: [] as string[]})
const settingsText = ref('{}'), credentials = ref<Record<string, string>>({}), filter = ref('')
let timer: ReturnType<typeof setInterval>, stream: EventSource | null = null
const active = computed(() => environments.value.find(e => e.id === workspace.activeEnvironment))
const adapter = computed(() => adapters.value.find(a => a.type === form.value.type))
const visible = computed(() => components.value.filter(c => (c.name+' '+c.type).toLowerCase().includes(filter.value.toLowerCase())))
const healthy = computed(() => components.value.filter(c => c.observation?.ok).length)
const enabled = computed(() => components.value.filter(c => c.enabled).length)
const nodes = computed(() => components.value.map((c, i) => ({...c, x: 25+(i%3)*235, y: 25+Math.floor(i/3)*108})))
const graphHeight = computed(() => Math.max(220, Math.ceil(nodes.value.length/3)*108+30))
const edges = computed(() => nodes.value.flatMap(n => n.dependencies.map(id => ({from: n, to: nodes.value.find(c => c.id===id)}))).filter(e => e.to))
const running = computed(() => investigation.value && ['queued','running'].includes(investigation.value.status))
const labels: Record<string,string> = {components:'Компоненты', topology:'Зависимости', investigations:'Расследования', completed:'Завершено', partial:'Неполные данные', failed:'Ошибка', running:'В работе', queued:'В очереди', cancelled:'Отменено', interrupted:'Прервано'}
function state(c: Component) { if (!c.enabled) return 'disabled'; if (!c.last_seen) return 'pending'; if (Date.now()-Date.parse(c.last_seen)>75000) return 'stale'; return c.observation?.ok ? 'healthy' : 'degraded' }
function stateLabel(c: Component) { return ({disabled:'Агент выключен',pending:'Запуск агента',stale:'Нет связи с агентом',healthy:'Доступен',degraded:'Ошибка проверки'})[state(c)] }
function date(value?: string) { return value ? new Date(value).toLocaleString('ru-RU') : 'Ещё не проверено' }
async function guarded(action: () => Promise<void>) { error.value=''; busy.value=true; try { await action() } catch(e) { const message=(e as Error).message; if(message==='AUTH') authenticated.value=false; else error.value=message } finally { busy.value=false } }
async function load() { environments.value=await api('/environments'); adapters.value=await api('/adapter-types'); authenticated.value=true; if(!workspace.activeEnvironment) workspace.activeEnvironment=environments.value[0]?.id || ''; await refresh() }
async function refresh() { if(!workspace.activeEnvironment) return; const id=workspace.activeEnvironment; const [cs,hs]=await Promise.all([api<Component[]>(`/environments/${id}/components`),api<Investigation[]>(`/environments/${id}/investigations`)]); if(id!==workspace.activeEnvironment) return; components.value=cs; history.value=hs; if(selected.value) selected.value=cs.find(c=>c.id===selected.value?.id)||null }
async function login() { await guarded(async()=>{ await api('/login','POST',{token:loginKey.value}); loginKey.value=''; await load() }) }
function navigate(view: string) { workspace.view=view; router.replace({query:{view}}) }
function openComponent(c?: Component) { editing.value=c?.id||''; form.value=c ? {name:c.name,type:c.type,endpoint:c.endpoint,web_url:c.web_url||'',description:c.description,enabled:c.enabled,dependencies:[...c.dependencies]} : {name:'',type:'http',endpoint:'',web_url:'',description:'',enabled:true,dependencies:[]}; settingsText.value=JSON.stringify(c?.settings||{health_path:'/health'},null,2); credentials.value={}; modal.value='component' }
function changeAdapter() { settingsText.value=JSON.stringify(adapter.value?.settings||{},null,2); credentials.value={} }
async function saveEnvironment() { await guarded(async()=>{ const env=await api<Environment>('/environments','POST',{name:envName.value,description:envDescription.value}); modal.value=null; envName.value=''; envDescription.value=''; workspace.activeEnvironment=env.id; await load() }) }
async function saveComponent() { await guarded(async()=>{ const body={...form.value,settings:JSON.parse(settingsText.value),secrets:Object.fromEntries(Object.entries(credentials.value).filter(([,v])=>v))}; await api(editing.value ? `/components/${editing.value}` : `/environments/${workspace.activeEnvironment}/components`,editing.value?'PUT':'POST',body); modal.value=null; await refresh() }) }
async function check(c: Component) { await guarded(async()=>{ await api(`/components/${c.id}/check`,'POST'); await refresh() }) }
async function remove(c: Component) { if(!confirm(`Отключить «${c.name}» от платформы? Целевая система останется на месте.`))return; await guarded(async()=>{await api(`/components/${c.id}`,'DELETE'); selected.value=null; await refresh()}) }
function watchInvestigation(job: Investigation) { investigation.value=job; stream?.close(); if(['queued','running'].includes(job.status)) { stream=new EventSource(`/api/investigations/${job.id}/events`); stream.onmessage=e=>{investigation.value=JSON.parse(e.data); if(!running.value){stream?.close(); refresh().catch(()=>{})}}; stream.onerror=()=>{stream?.close(); error.value='Поток прогресса прерван. Откройте расследование из истории.'} } }
async function start(direct=false) { await guarded(async()=>{ const id=direct?selected.value?.id:target.value; const path=direct?`/components/${id}/diagnoses`:`/environments/${workspace.activeEnvironment}/investigations`; const job=await api<Investigation>(path,'POST',{question:question.value,component_id:id||null,trace_id:trace.value||null,time_window_minutes:15}); watchInvestigation(job); navigate('investigations'); await refresh() }) }
function exportResult(format: 'json'|'md') { const job=investigation.value; if(!job)return; const a=job.assessment; const body=format==='json'?JSON.stringify(job,null,2):`# InfraAxon — ${job.request.question}\n\nStatus: ${job.status}\n\n${a?.summary||'Диагноз недоступен'}\n\n${a?.hypotheses.map(h=>`- ${h.cause}\n  Evidence: ${h.evidence_ids.join(', ')}`).join('\n')||''}\n\n## Evidence\n\n${job.results.flatMap(r=>r.evidence.map(e=>`### ${e.id}\n${r.component} · ${e.observed_at}\n\n\`\`\`json\n${e.data}\n\`\`\``)).join('\n\n')}`; const url=URL.createObjectURL(new Blob([body],{type:format==='json'?'application/json':'text/markdown'})); const link=document.createElement('a'); link.href=url; link.download=`infraaxon-${job.id}.${format}`; link.click(); setTimeout(()=>URL.revokeObjectURL(url),1000) }
watch(()=>workspace.activeEnvironment,()=>{components.value=[]; selected.value=null; investigation.value=null; stream?.close(); guarded(refresh)})
onMounted(()=>{guarded(load);timer=setInterval(()=>{if(authenticated.value)refresh().catch(()=>{})},10000)})
onUnmounted(()=>{clearInterval(timer);stream?.close()})
</script>

<template>
  <main v-if="!authenticated" class="login-shell">
    <div class="login-art"><div class="orbit"></div><div class="orbit small"></div><span class="axon-symbol">⌘</span></div>
    <form class="login-card" @submit.prevent="login"><div class="eyebrow">INFRASTRUCTURE INTELLIGENCE</div><h1>Infra<span>Axon</span></h1><p>Понимать инфраструктуру.<br>Находить причины. Видеть доказательства.</p><label>Ключ оператора<input v-model="loginKey" type="password" autocomplete="current-password" required placeholder="Ключ из локального .env"></label><button class="primary" :disabled="busy">Войти в платформу <span>→</span></button><p v-if="error" class="error">{{error}}</p><small>Локальные модели · Ваши данные · Проверяемые выводы</small></form>
  </main>
  <div v-else class="workspace">
    <aside class="sidebar"><a class="brand" href="/">◈ Infra<span>Axon</span></a><div class="eyebrow">WORKSPACE</div><label class="sr-only" for="environment">Окружение</label><select id="environment" v-model="workspace.activeEnvironment"><option disabled value="">Выберите окружение</option><option v-for="env in environments" :key="env.id" :value="env.id">{{env.name}}</option></select><button class="text-button" @click="modal='environment'">＋ Новое окружение</button><nav><button v-for="(icon,key) in {components:'▦',topology:'⑂',investigations:'◎'}" :key="key" :class="{active:workspace.view===key}" @click="navigate(key)"><span>{{icon}}</span>{{labels[key]}}<b v-if="key==='components'">{{components.length}}</b></button></nav><div class="sidebar-bottom"><span class="dot"></span> Локальный контур<small>InfraAxon / 0.1.0</small><button class="text-button" @click="guarded(async()=>{await api('/logout','POST');authenticated=false})">Выйти</button></div></aside>
    <section class="main-area">
      <header class="topbar"><span>Окружения <i>/</i> <strong>{{active?.name||'Начало работы'}}</strong></span><span class="pill">● LOCAL INFERENCE</span></header>
      <div class="content"><div v-if="error" role="alert" class="error banner">{{error}}<button @click="error=''">×</button></div>
      <div class="page-heading"><div><div class="eyebrow">{{workspace.view==='investigations'?'EVIDENCE-BASED DIAGNOSTICS':'INFRASTRUCTURE OVERVIEW'}}</div><h1>{{labels[workspace.view]}}</h1><p>{{active?.description||'Подключите инфраструктуру, чтобы начать наблюдение и диагностику.'}}</p></div><button v-if="workspace.activeEnvironment" class="primary" @click="openComponent()">＋ Подключить компонент</button><button v-else class="primary" @click="modal='environment'">＋ Создать окружение</button></div>
      <div class="stats"><div><span>Компоненты</span><strong>{{components.length.toString().padStart(2,'0')}}</strong><small>в текущем окружении</small></div><div><span>Успешные проверки</span><strong class="mint">{{healthy.toString().padStart(2,'0')}}</strong><small>по последним наблюдениям</small></div><div><span>Агенты включены</span><strong>{{enabled.toString().padStart(2,'0')}}</strong><small>специалисты по компонентам</small></div><div><span>Расследования</span><strong>{{history.length.toString().padStart(2,'0')}}</strong><small>история сохраняется локально</small></div></div>
      <template v-if="workspace.view==='components'">
        <div class="section-bar"><h2>Подключённая инфраструктура</h2><input v-model="filter" class="search" aria-label="Поиск компонентов" placeholder="Поиск по имени или типу…"></div>
        <div v-if="!components.length" class="empty"><div class="empty-icon">⑂</div><h2>Первое подключение</h2><p>Добавьте базу данных, брокер или приложение.<br>Для каждого компонента InfraAxon запустит своего агента.</p><button class="secondary" @click="workspace.activeEnvironment?openComponent():modal='environment'">Начать подключение →</button></div>
        <div class="component-grid">
          <article v-for="c in visible" :key="c.id" class="component-card" :aria-label="c.name">
            <div class="card-top"><span class="type-icon">{{c.type.slice(0,2).toUpperCase()}}</span><span :class="['status',state(c)]"><span class="dot"></span>{{stateLabel(c)}}</span></div>
            <h3><button class="component-title" @click="selected=c">{{c.name}}</button></h3>
            <span class="type-name">{{adapters.find(a=>a.type===c.type)?.name}}</span><code>{{c.endpoint}}</code>
            <div class="card-footer"><span>{{c.dependencies.length}} зависимостей</span><button class="text-button" @click="selected=c">Подробнее</button></div>
            <a v-if="c.web_url" class="service-link" :href="c.web_url" :title="c.web_url" target="_blank" rel="noopener noreferrer">Открыть сервис ↗<span class="sr-only"> — {{c.name}}, в новой вкладке</span></a>
          </article>
        </div>
      </template>
      <template v-if="workspace.view==='topology'"><div class="section-bar"><h2>Граф зависимостей</h2><span class="muted">Стрелка: компонент → его зависимость</span></div><div class="graph"><svg :style="{height:graphHeight+'px'}" :viewBox="`0 0 730 ${graphHeight}`" role="img" aria-label="Граф инфраструктуры"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#526477"/></marker></defs><path v-for="(edge,i) in edges" :key="i" :d="`M${edge.from.x+100},${edge.from.y+40} L${edge.to!.x+100},${edge.to!.y+40}`" stroke="#526477" fill="none" marker-end="url(#arrow)"/><g v-for="node in nodes" :key="node.id" class="graph-node" :transform="`translate(${node.x},${node.y})`" @click="selected=node"><rect width="205" height="76" rx="10"/><circle cx="18" cy="22" r="4" :fill="node.observation?.ok?'#62dfbc':'#c8a874'"/><text x="30" y="27">{{node.name.slice(0,22)}}</text><text x="16" y="54" class="graph-type">{{node.type}}</text></g></svg><p v-if="!nodes.length" class="muted">Добавьте компоненты и укажите связи в настройках подключения.</p></div></template>
      <template v-if="workspace.view==='investigations'">
        <form class="investigate-form panel" @submit.prevent="start()"><h2>Что происходит в инфраструктуре?</h2><textarea v-model="question" required placeholder="Опишите симптом: что перестало работать и когда это началось…"></textarea><div class="form-row"><select v-model="target" aria-label="Целевой компонент"><option value="">Координатор окружения</option><option v-for="c in components.filter(c=>c.enabled)" :key="c.id" :value="c.id">{{c.name}}</option></select><input v-model="trace" placeholder="Trace ID — необязательно" aria-label="Trace ID"><button class="primary" :disabled="busy||!!running||!enabled">Начать расследование →</button></div></form>
        <div class="investigation-layout"><aside class="history-list"><h2>История</h2><button v-for="job in history" :key="job.id" :class="{active:investigation?.id===job.id}" @click="watchInvestigation(job)"><strong>{{job.request.question}}</strong><small>{{labels[job.status]||job.status}} · {{date(job.created_at)}}</small></button><p v-if="!history.length" class="muted">Расследований пока нет.</p></aside><article v-if="investigation" class="panel result"><div class="section-bar"><span class="pill">{{labels[investigation.status]||investigation.status}}</span><div class="buttons"><button v-if="running" class="secondary" @click="guarded(async()=>{await api(`/investigations/${investigation!.id}/cancel`,'POST')})">Отменить</button><button class="text-button" @click="exportResult('json')">JSON ↓</button><button class="text-button" @click="exportResult('md')">Markdown ↓</button></div></div><h2>{{investigation.request.question}}</h2><p v-if="running" class="mint pulse">{{investigation.progress}}</p><p v-if="investigation.error" class="error">{{investigation.error}}</p><template v-if="investigation.assessment"><p class="summary">{{investigation.assessment.summary}}</p><h3>Гипотезы</h3><div v-for="(h,i) in investigation.assessment.hypotheses" :key="i" class="hypothesis"><b>{{i+1}}.</b><div>{{h.cause}}<small>Свидетельства: {{h.evidence_ids.join(', ')}}</small></div></div><h3>Следующие проверки</h3><ul><li v-for="n in investigation.assessment.next_checks" :key="n">{{n}}</li></ul><p v-for="n in investigation.assessment.missing_data" :key="n" class="muted">Недостающие данные: {{n}}</p></template><p v-else-if="!running" class="muted">Подтверждённого итогового диагноза нет. Ниже — доступные наблюдения.</p><div v-for="r in investigation.results" :key="r.component" class="specialist"><h3>{{r.component}}</h3><p v-if="r.error" class="error">{{r.error}}</p><p v-if="r.assessment">{{r.assessment.summary}}</p><details v-for="e in r.evidence" :key="e.id"><summary><span :class="e.ok?'mint':'amber'">{{e.ok?'●':'!'}} {{e.action}}</span> · {{e.duration_ms}} ms · {{date(e.observed_at)}}</summary><small>{{e.id}}</small><pre>{{e.data}}</pre></details></div></article><div v-else class="empty"><div class="empty-icon">◎</div><h2>От симптома к причине</h2><p>Специалисты сопоставят наблюдения<br>и приложат свидетельства к своим выводам.</p></div></div>
      </template>
      </div>
    </section>
    <div v-if="selected" class="drawer-backdrop" @click.self="selected=null"><aside class="drawer"><button class="close" aria-label="Закрыть" @click="selected=null">×</button><div class="eyebrow">COMPONENT DETAILS</div><h2>{{selected.name}}</h2><span :class="['status',state(selected)]">{{stateLabel(selected)}}</span><dl><dt>Тип</dt><dd>{{selected.type}}</dd><dt>Endpoint</dt><dd><code>{{selected.endpoint}}</code></dd><template v-if="selected.web_url"><dt>Веб-интерфейс</dt><dd><a class="service-link" :href="selected.web_url" :title="selected.web_url" target="_blank" rel="noopener noreferrer">Открыть сервис ↗<span class="sr-only"> — {{selected.name}}, в новой вкладке</span></a><span class="service-address">{{selected.web_url}}</span></dd></template><dt>Последний heartbeat</dt><dd>{{date(selected.last_seen)}}</dd><dt>Описание</dt><dd>{{selected.description||'Не задано'}}</dd></dl><div class="buttons"><button class="secondary" :disabled="busy" @click="check(selected)">Проверить</button><button class="secondary" @click="openComponent(selected)">Настроить</button></div><details v-if="selected.observation"><summary>Последнее наблюдение</summary><pre>{{selected.observation.data}}</pre></details><form @submit.prevent="start(true)"><label>Вопрос специалисту<textarea v-model="question" required placeholder="Что происходит с компонентом?"></textarea></label><button class="primary" :disabled="!selected.enabled||busy">Спросить агента →</button></form><button class="danger text-button" @click="remove(selected)">Удалить подключение</button></aside></div>
    <div v-if="modal" class="modal-backdrop" @click.self="modal=null"><form class="modal" @submit.prevent="modal==='environment'?saveEnvironment():saveComponent()"><button type="button" class="close" aria-label="Закрыть форму" @click="modal=null">×</button><div class="eyebrow">CONNECT YOUR INFRASTRUCTURE</div><h2>{{modal==='environment'?'Новое окружение':editing?'Настройка компонента':'Подключить компонент'}}</h2><template v-if="modal==='environment'"><label>Название окружения<input v-model="envName" required placeholder="Например, Development"></label><label>Описание<textarea v-model="envDescription" placeholder="Назначение и особенности окружения"></textarea></label></template><template v-else><div class="form-row"><label>Название<input v-model="form.name" required placeholder="Например, Main database"></label><label>Тип<select v-model="form.type" @change="changeAdapter"><option v-for="a in adapters" :key="a.type" :value="a.type">{{a.name}}</option></select></label></div><label>Endpoint<input v-model="form.endpoint" required placeholder="Адрес, доступный из сети агентов"></label><label>Адрес веб-интерфейса<input v-model="form.web_url" type="url" maxlength="2048" placeholder="Например, http://localhost:13000" aria-describedby="web-url-help"></label><p id="web-url-help" class="field-help">Необязательно. Адрес для открытия сервиса в браузере.</p><label>Назначение и инструкции<textarea v-model="form.description" placeholder="За что отвечает компонент, что считать нормой"></textarea></label><label>Параметры адаптера (JSON)<textarea class="code-input" v-model="settingsText" spellcheck="false"></textarea></label><div class="form-row"><label v-for="field in adapter?.secret_fields" :key="field">{{field}}<input v-model="credentials[field]" type="password" autocomplete="new-password" :placeholder="editing?'Пусто — оставить прежнее':'Необязательно'"></label></div><label>Зависимости<select v-model="form.dependencies" multiple><option v-for="c in components.filter(c=>c.id!==editing)" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label class="checkbox"><input type="checkbox" v-model="form.enabled"> Запустить специализированного агента</label></template><p v-if="error" class="error">{{error}}</p><div class="modal-footer"><button type="button" class="secondary" @click="modal=null">Отмена</button><button class="primary" :disabled="busy">{{busy?'Сохранение…':'Сохранить'}}</button></div></form></div>
  </div>
</template>
