<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App"/><PackageReference Include="MongoDB.Driver" Version="3.11.1"/><PackageReference Include="StackExchange.Redis" Version="3.1.31"/><PackageReference Include="AWSSDK.S3" Version="4.0.103"/><PackageReference Include="Confluent.Kafka" Version="2.15.0"/><PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0"/><PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0"/><PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0"/><PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0"/></ItemGroup></Project>
